// demos/react-app/src/playground/RootEditor.tsx
import { ChangeEvent } from 'react';
import { useRootEditor } from 'sequential-workflow-designer-react';
import { WorkflowDefinition } from './model';

export function RootEditor() {
	const { properties, setProperty, isReadonly } = useRootEditor<WorkflowDefinition>();

	function onAlfaChanged(e: ChangeEvent) {
		setProperty('alfa', (e.target as HTMLInputElement).value);
	}

	return (
		<>
			<h2>Root editor</h2>

			<h4>Alfa</h4>

			<input type="text" value={properties.alfa || ''} readOnly={isReadonly} onChange={onAlfaChanged} />
		</>
	);
}

// demos/svelte-app/src/routes/root-editor.svelte
<script lang="ts">
	import type { RootEditorContext, Definition } from 'sequential-workflow-designer';

	export let context: RootEditorContext;
	export let definition: Definition;
	export let isReadonly: boolean;

	let velocity = definition.properties.velocity;

	$: {
		console.log('Changed', { velocity });
	}

	function onVelocityChanged(event: Event) {
		velocity = parseInt((event.target as HTMLInputElement).value);
		definition.properties.velocity = velocity;
		context.notifyPropertiesChanged();
	}
</script>

<h2>Root Editor</h2>

<h3>Velocity</h3>

<input type="number" value={String(velocity)} readonly={isReadonly} on:input={onVelocityChanged} />
