// demos/angular-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import {
	Definition,
	Designer,
	GlobalEditorContext,
	Properties,
	Step,
	StepEditorContext,
	StepsConfiguration,
	ToolboxConfiguration,
	ValidatorConfiguration
} from 'sequential-workflow-designer';

function createDefinition() {
	return {
		properties: {
			velocity: 0
		},
		sequence: []
	};
}

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
	private designer?: Designer;

	public definition: Definition = createDefinition();
	public definitionJSON?: string;
	public isValid?: boolean;

	public readonly toolboxConfiguration: ToolboxConfiguration = {
		groups: [
			{
				name: 'Step',
				steps: [
					{
						componentType: 'task',
						name: 'Step',
						properties: { velocity: 0 },
						type: 'task'
					}
				]
			}
		]
	};
	public readonly stepsConfiguration: StepsConfiguration = {
		iconUrlProvider: () => './assets/angular-icon.svg'
	};
	public readonly validatorConfiguration: ValidatorConfiguration = {
		step: (step: Step) => !!step.name && Number(step.properties['velocity']) >= 0,
		root: (definition: Definition) => Number(definition.properties['velocity']) >= 0
	};

	public ngOnInit() {
		this.updateDefinitionJSON();
	}

	public onDesignerReady(designer: Designer) {
		this.designer = designer;
		this.updateIsValid();
		console.log('designer ready', this.designer);
	}

	public onDefinitionChanged(definition: Definition) {
		this.definition = definition;
		this.updateIsValid();
		this.updateDefinitionJSON();
		console.log('definition changed');
	}

	public updateName(step: Step, event: Event, context: StepEditorContext) {
		step.name = (event.target as HTMLInputElement).value;
		context.notifyNameChanged();
	}

	public updateProperty(properties: Properties, name: string, event: Event, context: GlobalEditorContext | StepEditorContext) {
		properties[name] = (event.target as HTMLInputElement).value;
		context.notifyPropertiesChanged();
	}

	public reloadDefinitionClicked() {
		this.definition = createDefinition();
		this.updateDefinitionJSON();
	}

	private updateDefinitionJSON() {
		this.definitionJSON = JSON.stringify(this.definition, null, 2);
	}

	private updateIsValid() {
		this.isValid = this.designer?.isValid();
	}
}

<sqd-designer
	theme="light"
	[undoStackSize]="10"
	[definition]="definition"
	[toolboxConfiguration]="toolboxConfiguration"
	[stepsConfiguration]="stepsConfiguration"
	[validatorConfiguration]="validatorConfiguration"
	[controlBar]="true"
	[areEditorsHidden]="false"
	[globalEditor]="globalEditor"
	[stepEditor]="stepEditor"
	(onReady)="onDesignerReady($event)"
	(onDefinitionChanged)="onDefinitionChanged($event)"
>
</sqd-designer>

<ng-template #globalEditor let-editor>
	<h2>Global Editor</h2>

	<h3>Velocity</h3>
	<input
		type="number"
		[value]="editor.definition.properties.velocity"
		(input)="updateProperty(editor.definition.properties, 'velocity', $event, editor.context)"
	/>
</ng-template>

<ng-template #stepEditor let-editor>
	<h2>Step Editor</h2>

	<h3>Name</h3>
	<input type="text" [value]="editor.step.name" (input)="updateName(editor.step, $event, editor.context)" />

	<h3>Velocity</h3>
	<input
		type="number"
		[value]="editor.step.properties.velocity"
		(input)="updateProperty(editor.step.properties, 'velocity', $event, editor.context)"
	/>
</ng-template>

<br />

<button (click)="reloadDefinitionClicked()">Reload definition</button>

<br />

<textarea cols="60" rows="18">{{ definitionJSON }}</textarea>

<br />

Is valid: {{ isValid }}

// demos/react-app/src/App.tsx
import { useEffect, useState } from 'react';
import { ObjectCloner, Step, StepsConfiguration, ToolboxConfiguration, ValidatorConfiguration } from 'sequential-workflow-designer';
import { SequentialWorkflowDesigner, wrapDefinition } from 'sequential-workflow-designer-react';
import { GlobalEditor } from './GlobalEditor';
import { StepEditor } from './StepEditor';
import { createSwitchStep, createTaskStep } from './StepUtils';
import { WorkflowDefinition } from './model';
import { useSequentialWorkflowDesignerController } from 'sequential-workflow-designer-react';

const startDefinition: WorkflowDefinition = {
	properties: {
		alfa: 'bravo'
	},
	sequence: [createTaskStep(), createSwitchStep()]
};

const toolboxConfiguration: ToolboxConfiguration = {
	groups: [{ name: 'Steps', steps: [createTaskStep(), createSwitchStep()] }]
};

const stepsConfiguration: StepsConfiguration = {
	iconUrlProvider: () => null
};

const validatorConfiguration: ValidatorConfiguration = {
	step: (step: Step) => Boolean(step.name),
	root: (definition: WorkflowDefinition) => Boolean(definition.properties.alfa)
};

export function App() {
	const controller = useSequentialWorkflowDesignerController();
	const [isVisible, setIsVisible] = useState(true);
	const [definition, setDefinition] = useState(() => wrapDefinition(startDefinition));
	const [selectedStepId, setSelectedStepId] = useState<string | null>(null);
	const [isReadonly, setIsReadonly] = useState(false);
	const definitionJson = JSON.stringify(definition.value, null, 2);

	useEffect(() => {
		console.log(`definition updated, isValid=${definition.isValid}`);
	}, [definition]);

	function toggleVisibilityClicked() {
		setIsVisible(!isVisible);
	}

	function toggleSelectionClicked() {
		const id = definition.value.sequence[0].id;
		setSelectedStepId(selectedStepId ? null : id);
	}

	function toggleIsReadonlyClicked() {
		setIsReadonly(!isReadonly);
	}

	function moveViewportToFirstStepClicked() {
		const fistStep = definition.value.sequence[0];
		if (fistStep) {
			controller.moveViewportToStep(fistStep.id);
		}
	}

	function reloadDefinitionClicked() {
		const newDefinition = ObjectCloner.deepClone(startDefinition);
		setDefinition(wrapDefinition(newDefinition));
	}

	return (
		<>
			{isVisible && (
				<SequentialWorkflowDesigner
					undoStackSize={10}
					definition={definition}
					onDefinitionChange={setDefinition}
					selectedStepId={selectedStepId}
					isReadonly={isReadonly}
					onSelectedStepIdChanged={setSelectedStepId}
					toolboxConfiguration={toolboxConfiguration}
					stepsConfiguration={stepsConfiguration}
					validatorConfiguration={validatorConfiguration}
					controlBar={true}
					globalEditor={<GlobalEditor />}
					stepEditor={<StepEditor />}
					controller={controller}
				/>
			)}

			<ul>
				<li>Definition: {definitionJson.length} bytes</li>
				<li>Selected step: {selectedStepId}</li>
				<li>Is readonly: {isReadonly ? '✅ Yes' : 'No'}</li>
				<li>Is valid: {definition.isValid === undefined ? '?' : definition.isValid ? '✅ Yes' : '⛔ No'}</li>
			</ul>

			<div>
				<button onClick={toggleVisibilityClicked}>Toggle visibility</button>
				<button onClick={reloadDefinitionClicked}>Reload definition</button>
				<button onClick={toggleSelectionClicked}>Toggle selection</button>
				<button onClick={toggleIsReadonlyClicked}>Toggle readonly</button>
				<button onClick={moveViewportToFirstStepClicked}>Move viewport to first step</button>
			</div>

			<div>
				<textarea value={definitionJson} readOnly={true} cols={100} rows={15} />
			</div>
		</>
	);
}
