// demos/svelte-app/src/routes/step-editor.svelte
<script lang="ts">
	import type { StepEditorContext, Definition, Step } from 'sequential-workflow-designer';

	export let context: StepEditorContext;
	export let definition: Definition;
	export let step: Step;

	let name = step.name;
	let comment = step.properties.comment;

	$: {
		console.log('Changed', { definition, name, comment });
	}

	function onNameChanged(event: Event) {
		name = (event.target as HTMLInputElement).value;
		step.name = name;
		context.notifyNameChanged();
	}

	function onCommentChanged(event: Event) {
		comment = (event.target as HTMLInputElement).value;
		step.properties.comment = comment;
		context.notifyPropertiesChanged();
	}
</script>

<h2>Step Editor {step.type}</h2>

<h3>Name</h3>

<input value={name} on:input={onNameChanged} />

<h3>Comment</h3>

<input value={comment} on:input={onCommentChanged} />

// demos/react-app/src/StepEditor.tsx
import { ChangeEvent } from 'react';
import { SwitchStep } from 'sequential-workflow-designer';
import { useStepEditor } from 'sequential-workflow-designer-react';

export function StepEditor() {
	const { type, name, step, properties, setName, setProperty, notifyPropertiesChanged, notifyChildrenChanged } = useStepEditor();

	function onNameChanged(e: ChangeEvent) {
		setName((e.target as HTMLInputElement).value);
	}

	function onXChanged(e: ChangeEvent) {
		setProperty('x', (e.target as HTMLInputElement).value);
	}

	function onYChanged(e: ChangeEvent) {
		properties['y'] = (e.target as HTMLInputElement).value;
		notifyPropertiesChanged();
	}

	function toggleExtraBranch() {
		const switchStep = step as SwitchStep;
		if (switchStep.branches['extra']) {
			delete switchStep.branches['extra'];
		} else {
			switchStep.branches['extra'] = [];
		}
		notifyChildrenChanged();
	}

	return (
		<>
			<h2>Step Editor {type}</h2>

			<h4>Name</h4>
			<input type="text" value={name} onChange={onNameChanged} />

			<h4>X Variable</h4>
			<input type="text" value={(properties['x'] as string) || ''} onChange={onXChanged} />

			<h4>Y Variable</h4>
			<input type="text" value={(properties['y'] as string) || ''} onChange={onYChanged} />

			{type === 'switch' && (
				<>
					<h4>Extra branch</h4>
					<button onClick={toggleExtraBranch}>Toggle branch</button>
				</>
			)}
		</>
	);
}
