// react/src/SequentialWorkflowDesigner.tsx
import ReactDOM from 'react-dom/client';
import { useEffect, useRef, useState, isValidElement } from 'react';
import {
	Definition,
	ToolboxConfiguration,
	Designer,
	RootEditorContext,
	Step,
	StepEditorContext,
	StepsConfiguration,
	DesignerExtension,
	CustomActionHandler,
	CustomActionHandlerContext,
	CustomAction,
	Sequence,
	ValidatorConfiguration,
	RootEditorProvider,
	StepEditorProvider,
	KeyboardConfiguration,
	I18n,
	PreferenceStorage,
	PlaceholderConfiguration
} from 'sequential-workflow-designer';
import { RootEditorWrapperContext } from './RootEditorWrapper';
import { StepEditorWrapperContext } from './StepEditorWrapper';
import { wrapDefinition, WrappedDefinition } from './WrappedDefinition';
import { Presenter } from './core/Presenter';
import { SequentialWorkflowDesignerController } from './SequentialWorkflowDesignerController';

const externalEditorClassName = 'sqd-editor-react';

export type ReactToolboxConfiguration = Omit<ToolboxConfiguration, 'isCollapsed'>;

export interface SequentialWorkflowDesignerProps<TDefinition extends Definition> {
	definition: WrappedDefinition<TDefinition>;
	onDefinitionChange: (state: WrappedDefinition<TDefinition>) => void;
	selectedStepId?: string | null;
	onSelectedStepIdChanged?: (stepId: string | null) => void;
	onStepUnselectionBlocked?: (targetStepId: string | null) => void;
	isReadonly?: boolean;

	rootEditor: false | JSX.Element | RootEditorProvider;
	stepEditor: false | JSX.Element | StepEditorProvider;
	isEditorCollapsed?: boolean;
	onIsEditorCollapsedChanged?: (isCollapsed: boolean) => void;

	theme?: string;
	undoStackSize?: number;
	stepsConfiguration: StepsConfiguration;
	validatorConfiguration?: ValidatorConfiguration;
	placeholderConfiguration?: PlaceholderConfiguration;
	toolboxConfiguration: false | ReactToolboxConfiguration;
	isToolboxCollapsed?: boolean;
	onIsToolboxCollapsedChanged?: (isCollapsed: boolean) => void;
	/**
	 * @description If true, the control bar will be displayed.
	 */
	controlBar: boolean;
	contextMenu?: boolean;
	keyboard?: boolean | KeyboardConfiguration;
	preferenceStorage?: PreferenceStorage;
	controller?: SequentialWorkflowDesignerController;
	customActionHandler?: CustomActionHandler;
	extensions?: DesignerExtension[];
	i18n?: I18n;
}

export function SequentialWorkflowDesigner<TDefinition extends Definition>(props: SequentialWorkflowDesignerProps<TDefinition>) {
	const [root, setRoot] = useState<HTMLElement | null>(null);

	const onDefinitionChangeRef = useRef(props.onDefinitionChange);
	const onSelectedStepIdChangedRef = useRef(props.onSelectedStepIdChanged);
	const onStepUnselectionBlockedRef = useRef(props.onStepUnselectionBlocked);
	const onIsEditorCollapsedChangedRef = useRef(props.onIsEditorCollapsedChanged);
	const onIsToolboxCollapsedChangedRef = useRef(props.onIsToolboxCollapsedChanged);
	const rootEditorRef = useRef(props.rootEditor);
	const stepEditorRef = useRef(props.stepEditor);
	const controllerRef = useRef(props.controller);
	const customActionHandlerRef = useRef(props.customActionHandler);

	const designerRef = useRef<Designer<TDefinition> | null>(null);
	const editorRootRef = useRef<ReactDOM.Root | null>(null);

	const definition = props.definition;
	const selectedStepId = props.selectedStepId;
	const isReadonly = props.isReadonly;
	const theme = props.theme;
	const undoStackSize = props.undoStackSize;
	const steps = props.stepsConfiguration;
	const validator = props.validatorConfiguration;
	const placeholder = props.placeholderConfiguration;
	const toolbox = props.toolboxConfiguration;
	const isEditorCollapsed = props.isEditorCollapsed;
	const isToolboxCollapsed = props.isToolboxCollapsed;
	const controlBar = props.controlBar;
	const contextMenu = props.contextMenu;
	const keyboard = props.keyboard;
	const preferenceStorage = props.preferenceStorage;
	const extensions = props.extensions;
	const i18n = props.i18n;

	function forwardDefinition() {
		if (designerRef.current) {
			const wd = wrapDefinition(designerRef.current.getDefinition(), designerRef.current.isValid());
			onDefinitionChangeRef.current(wd);
		}
	}

	function rootEditorProvider(def: TDefinition, context: RootEditorContext, isReadonly: boolean) {
		if (!rootEditorRef.current) {
			throw new Error('Root editor is not provided');
		}
		if (isValidElement(rootEditorRef.current)) {
			return Presenter.render(
				externalEditorClassName,
				editorRootRef,
				<RootEditorWrapperContext definition={def} context={context} isReadonly={isReadonly}>
					{rootEditorRef.current}
				</RootEditorWrapperContext>
			);
		}
		return (rootEditorRef.current as RootEditorProvider)(def, context, isReadonly);
	}

	function stepEditorProvider(step: Step, context: StepEditorContext, def: Definition, isReadonly: boolean) {
		if (!stepEditorRef.current) {
			throw new Error('Step editor is not provided');
		}
		if (isValidElement(stepEditorRef.current)) {
			return Presenter.render(
				externalEditorClassName,
				editorRootRef,
				<StepEditorWrapperContext step={step} definition={def} context={context} isReadonly={isReadonly}>
					{stepEditorRef.current}
				</StepEditorWrapperContext>
			);
		}
		return (stepEditorRef.current as StepEditorProvider)(step, context, def, isReadonly);
	}

	function customActionHandler(action: CustomAction, step: Step | null, sequence: Sequence, context: CustomActionHandlerContext) {
		if (customActionHandlerRef.current) {
			customActionHandlerRef.current(action, step, sequence, context);
		}
	}

	function tryDestroy() {
		Presenter.tryDestroy(editorRootRef);

		if (controllerRef.current) {
			controllerRef.current.setDesigner(null);
		}
		if (designerRef.current) {
			designerRef.current.destroy();
			designerRef.current = null;
			// console.log('sqd: designer destroyed');
		}
	}

	useEffect(() => {
		onDefinitionChangeRef.current = props.onDefinitionChange;
	}, [props.onDefinitionChange]);

	useEffect(() => {
		onSelectedStepIdChangedRef.current = props.onSelectedStepIdChanged;
	}, [props.onSelectedStepIdChanged]);

	useEffect(() => {
		onStepUnselectionBlockedRef.current = props.onStepUnselectionBlocked;
	}, [props.onStepUnselectionBlocked]);

	useEffect(() => {
		onIsEditorCollapsedChangedRef.current = props.onIsEditorCollapsedChanged;
	}, [props.onIsEditorCollapsedChanged]);

	useEffect(() => {
		onIsToolboxCollapsedChangedRef.current = props.onIsToolboxCollapsedChanged;
	}, [props.onIsToolboxCollapsedChanged]);

	useEffect(() => {
		rootEditorRef.current = props.rootEditor;
	}, [props.rootEditor]);

	useEffect(() => {
		stepEditorRef.current = props.stepEditor;
	}, [props.stepEditor]);

	useEffect(() => {
		customActionHandlerRef.current = props.customActionHandler;
	}, [props.customActionHandler]);

	useEffect(() => {
		if (!root) {
			return;
		}

		if (designerRef.current) {
			const isNotChanged = definition.value === designerRef.current.getDefinition();
			if (isNotChanged) {
				if (selectedStepId !== undefined && selectedStepId !== designerRef.current.getSelectedStepId()) {
					if (selectedStepId) {
						designerRef.current.selectStepById(selectedStepId);
					} else {
						designerRef.current.clearSelectedStep();
					}
					// console.log('sqd: selected step updated');
				}

				if (isReadonly !== undefined && isReadonly !== designerRef.current.isReadonly()) {
					designerRef.current.setIsReadonly(isReadonly);
					// console.log('sqd: isReadonly updated');
				}
				if (isToolboxCollapsed !== undefined && isToolboxCollapsed !== designerRef.current.isToolboxCollapsed()) {
					designerRef.current.setIsToolboxCollapsed(isToolboxCollapsed);
					// console.log('sqd: isToolboxCollapsed updated');
				}
				if (isEditorCollapsed !== undefined && isEditorCollapsed !== designerRef.current.isEditorCollapsed()) {
					designerRef.current.setIsEditorCollapsed(isEditorCollapsed);
					// console.log('sqd: isEditorCollapsed updated');
				}
				return;
			}

			tryDestroy();
		}

		const designer = Designer.create(root, definition.value, {
			theme,
			undoStackSize,
			toolbox: toolbox
				? {
						...toolbox,
						isCollapsed: isToolboxCollapsed
					}
				: false,
			steps,
			validator,
			placeholder,
			controlBar,
			contextMenu,
			keyboard,
			preferenceStorage,
			editors:
				rootEditorRef.current && stepEditorRef.current
					? {
							isCollapsed: isEditorCollapsed,
							rootEditorProvider,
							stepEditorProvider
						}
					: false,
			customActionHandler: customActionHandlerRef.current && customActionHandler,
			extensions,
			i18n,
			isReadonly
		});
		if (controllerRef.current) {
			controllerRef.current.setDesigner(designer as unknown as Designer<Definition>);
		}
		if (selectedStepId) {
			designer.selectStepById(selectedStepId);
		}
		// console.log('sqd: designer rendered');

		designer.onReady.subscribe(forwardDefinition);
		designer.onDefinitionChanged.subscribe(forwardDefinition);

		designer.onSelectedStepIdChanged.subscribe(stepId => {
			if (onSelectedStepIdChangedRef.current) {
				onSelectedStepIdChangedRef.current(stepId);
			}
		});
		designer.onStepUnselectionBlocked.subscribe(targetStepId => {
			if (onStepUnselectionBlockedRef.current) {
				onStepUnselectionBlockedRef.current(targetStepId);
			}
		});
		designer.onIsToolboxCollapsedChanged.subscribe(isCollapsed => {
			if (onIsToolboxCollapsedChangedRef.current) {
				onIsToolboxCollapsedChangedRef.current(isCollapsed);
			}
		});
		designer.onIsEditorCollapsedChanged.subscribe(isCollapsed => {
			if (onIsEditorCollapsedChangedRef.current) {
				onIsEditorCollapsedChangedRef.current(isCollapsed);
			}
		});

		designerRef.current = designer;
	}, [
		root,
		definition,
		selectedStepId,
		isReadonly,
		theme,
		undoStackSize,
		toolbox,
		isToolboxCollapsed,
		isEditorCollapsed,
		contextMenu,
		keyboard,
		preferenceStorage,
		controlBar,
		steps,
		validator,
		placeholder,
		extensions,
		i18n
	]);

	useEffect(() => {
		return tryDestroy;
	}, []);

	return <div ref={setRoot} data-testid="designer" className="sqd-designer-react"></div>;
}

// svelte/src/lib/SequentialWorkflowDesigner.svelte
<script lang="ts">
	import { onMount, onDestroy, createEventDispatcher } from 'svelte';
	import {
		Designer,
		DefinitionWalker,
		type Definition,
		type StepsConfiguration,
		type ToolboxConfiguration,
		type Step,
		type StepEditorContext,
		type RootEditorContext,
		type UndoStack,
		type ValidatorConfiguration,
		type PlaceholderConfiguration,
		type UidGenerator,
		type DesignerExtension,
		type EditorsConfiguration,
		type CustomActionHandler,
		type StepEditorProvider,
		type RootEditorProvider,
		type KeyboardConfiguration,
		type I18n,
		type PreferenceStorage
	} from 'sequential-workflow-designer';

	const dispatch = createEventDispatcher<{
		definitionChanged: {
			definition: Definition;
			isValid: boolean;
		};
		selectedStepIdChanged: {
			stepId: string | null;
		};
		stepUnselectionBlocked: {
			targetStepId: string | null;
		};
		isToolboxCollapsedChanged: {
			isCollapsed: boolean;
		};
		isEditorCollapsedChanged: {
			isCollapsed: boolean;
		};
	}>();

	export let definition: Definition;
	export let steps: StepsConfiguration;
	export let toolbox: Omit<ToolboxConfiguration, 'isCollapsed'> | false = false;
	export let isToolboxCollapsed = false;
	export let controlBar = true;
	export let theme = 'light';
	export let contextMenu = true;
	export let keyboard: boolean | KeyboardConfiguration | undefined = undefined;
	export let preferenceStorage: PreferenceStorage | undefined = undefined;
	export let undoStackSize: number | undefined = undefined;
	export let undoStack: UndoStack | undefined = undefined;
	export let validator: ValidatorConfiguration | undefined = undefined;
	export let placeholder: PlaceholderConfiguration | undefined = undefined;
	export let definitionWalker: DefinitionWalker | undefined = undefined;
	export let extensions: DesignerExtension[] | undefined = undefined;
	export let i18n: I18n | undefined = undefined;
	export let uidGenerator: UidGenerator | undefined = undefined;
	export let customActionHandler: CustomActionHandler | undefined = undefined;

	/**
	 * @description Svelte component that will be used to render the step editor. If this property is set, the `nativeStepEditor` property will be ignored.
	 */
	export let stepEditor: ConstructorOfATypedSvelteComponent | null = null;
	/**
	 * @description Function that will be used to render the step editor.
	 */
	export let nativeStepEditor: StepEditorProvider | null = null;
	/**
	 * @description Svelte component that will be used to render the root editor. If this property is set, the `nativeRootEditor` property will be ignored.
	 */
	export let rootEditor: ConstructorOfATypedSvelteComponent | null = null;
	/**
	 * @description Function that will be used to render the root editor.
	 */
	export let nativeRootEditor: RootEditorProvider | null = null;

	export let isEditorCollapsed = false;
	export let isReadonly = false;
	export let selectedStepId: string | null = null;

	let isFirstChange = true;
	let designer: Designer | null = null;
	let root: HTMLElement;

	function init() {
		const editors: EditorsConfiguration | false =
			(stepEditor || nativeStepEditor) && (rootEditor || nativeRootEditor)
				? {
						isCollapsed: isEditorCollapsed,
						stepEditorProvider: (step: Step, context: StepEditorContext, def: Definition, isReadonly: boolean) => {
							if (stepEditor) {
								const root = document.createElement('div');
								new stepEditor({
									target: root,
									props: { step, context, definition: def, isReadonly }
								});
								return root;
							}
							if (nativeStepEditor) {
								return nativeStepEditor(step, context, def, isReadonly);
							}
							throw new Error('No step editor provided');
						},
						rootEditorProvider: (def: Definition, context: RootEditorContext, isReadonly: boolean) => {
							if (rootEditor) {
								const root = document.createElement('div');
								new rootEditor({
									target: root,
									props: { definition: def, context, isReadonly }
								});
								return root;
							}
							if (nativeRootEditor) {
								return nativeRootEditor(def, context, isReadonly);
							}
							throw new Error('No root editor provided');
						}
					}
				: false;
		const _toolbox: ToolboxConfiguration | false = toolbox
			? {
					...toolbox,
					isCollapsed: isToolboxCollapsed
				}
			: false;

		const d = Designer.create(root, definition, {
			steps,
			controlBar,
			toolbox: _toolbox,
			editors,
			theme,
			contextMenu,
			keyboard,
			preferenceStorage,
			undoStackSize,
			undoStack,
			validator,
			placeholder,
			definitionWalker,
			extensions,
			isReadonly,
			i18n,
			uidGenerator,
			customActionHandler
		});
		d.onReady.subscribe(() =>
			dispatch('definitionChanged', {
				definition: d.getDefinition(),
				isValid: d.isValid()
			})
		);
		d.onDefinitionChanged.subscribe(definition =>
			dispatch('definitionChanged', {
				definition,
				isValid: d.isValid()
			})
		);
		d.onSelectedStepIdChanged.subscribe(stepId => dispatch('selectedStepIdChanged', { stepId }));
		d.onStepUnselectionBlocked.subscribe(targetStepId => dispatch('stepUnselectionBlocked', { targetStepId }));
		d.onIsToolboxCollapsedChanged.subscribe(isCollapsed => dispatch('isToolboxCollapsedChanged', { isCollapsed }));
		d.onIsEditorCollapsedChanged.subscribe(isCollapsed => dispatch('isEditorCollapsedChanged', { isCollapsed }));

		if (selectedStepId) {
			d.selectStepById(selectedStepId);
		}
		return d;
	}

	onMount(() => {
		designer = init();
	});

	$: {
		if (designer) {
			const isDefinitionChanged = !isFirstChange && definition !== designer.getDefinition();
			if (isDefinitionChanged) {
				designer.destroy();
				designer = init();
			} else {
				isFirstChange = false;

				if (isReadonly !== designer.isReadonly()) {
					designer.setIsReadonly(isReadonly);
				}
				if (selectedStepId !== designer.getSelectedStepId()) {
					if (selectedStepId) {
						designer.selectStepById(selectedStepId);
					} else {
						designer.clearSelectedStep();
					}
				}
				if (isEditorCollapsed !== designer.isEditorCollapsed()) {
					designer.setIsEditorCollapsed(isEditorCollapsed);
				}
				if (isToolboxCollapsed !== designer.isToolboxCollapsed()) {
					designer.setIsToolboxCollapsed(isToolboxCollapsed);
				}
			}
		}
	}

	onDestroy(() => {
		if (designer) {
			designer.destroy();
			designer = null;
		}
	});
</script>

<div bind:this={root} class="sqd-designer-svelte" />
